sudo: false
language: java
jdk: openjdk7
notifications:
  email: false
  webhooks:
    - http://n.tkte.ch/h/3963/Jc_w-9YHlHzyyPQDh_E72EHB
install: true
script:
  - gradle setupCIWorkspace
  - gradle build -PbuildNumber=$TRAVIS_BUILD_NUMBER
after_success:
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == AlmuraDev/AlmuraSDK ]] && [[ $TRAVIS_BRANCH == master ]] && gradle uploadArchives"
env:
  global:
    - secure: "RL2m5gKOsNr/nsPD3tNW0AbcMJKF91m+3pDDwPQsTYuahmZaRg4BBUiO6b/B6wD164zW9LWjEDuDEhH534Zzjarwdtb8LBJapQMGcFV9Kb7gjfxTiQ69CVaFmBsKKZj8el5wNYXeoH1qjVXsxmQ+4C5UaU/8zzQcTO2I1OhdkFs="
    - secure: "gErqVTEoWWqj/0Zbz2CkuysOnjeoRm4fJZYEDlh2mhAYxYxi875OQpa6lsFAoz+kt7PeBOepuuJ8wPSMGkHAVcML2EMMgp3Y2mMlZ8uYWIGm75PKgMR7qZkrd5lOJu6bj/q132rq36StWy3GyQJnB6pNDTmiH8CgPI7qs6UMaIw="